apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secretproviderclass.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - podmonitor.yaml

images:
  - name: todo-api
    newName: REPLACED_BY_OVERLAY
    newTag: latest
